### ISSUE TITLE
/api/osd/update does not work when trying to set only *changed flags.

### ISSUE THREAD

**Issue by boris-horner** [dewarim/cinnamon4#398]
The following request to `/api/osd/update` works.
```
<updateOsdRequest>
    <updateContentChanged>false</updateContentChanged>
    <updateMetadataChanged>true</updateMetadataChanged>
    <osds>
        <osd>
            <id>347442</id>
            <name>3269910</name>
      <metadataChanged>true</metadataChanged>
    </osd>
  </osds>
</updateOsdRequest>
```

If I remove the name element, I get an `INVALID_REQUEST`.

**Comment by dewarim** [comment]
Currently the request code expects an update request to change a field of the OSD, but does not take into consideration that the ...changed elements are also fields of the OSD.
